---
title: "APS Aim 7 Derived Variables Summary"
output: github_document
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r, echo = FALSE}
load(file = "tmp-data/20250731_data.RData")
```

```{r, echo = FALSE}
# Source variable derivation code
source("R/all.R")
```

```{r, echo = FALSE}
summarize_factor_variable <- function(var) {
  sum_table <- summary(as.factor(var))
  total <- sum(sum_table)
  var_summary <- data.frame(
    counts = sum_table,
    percentage = paste0(round(sum_table / total * 100, 2), "%")
  )
  knitr::kable(var_summary, col.names = c("Value", "Counts", "% of Data"))
}
```

## Neuromuscular Blockade
```{r, echo = FALSE}
nmb_0 <- derive_neuromuscular_blockade_0(data)
summarize_factor_variable(nmb_0)
```

## Inflammatory Profile (Streamlined)

```{r, echo = FALSE}
ifp_0 <- derive_inflammatory_profile_0(data)
summarize_factor_variable(ifp_0)
```

## Respiratory Failure Severity (Systematic)

```{r, echo = FALSE}
rfs_0 <- derive_respiratory_failure_severity_0(data)
```

### Variable 1
```{r, echo = FALSE}
summarize_factor_variable(rfs_0$rfs_var1)
```

### Variable 2
```{r, echo = FALSE}
hist(rfs_0$rfs_var2, main = "Histogram of Variable 2 (Systematic)", xlab = "Variable 2")
```

